spring:
    application:
        name: ${APP_NAME:be-service}
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/nghien-cuu-khoa-hoc-2025}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:123456}
    main:
        allow-bean-definition-overriding: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: ${CHANGE_LOG:classpath:db/changelogs/master-changelog.xml}
        enabled: true
server:
    port: ${PORT:8386}